### ISSUE TITLE
Unable to `pip` install - mlflow_tools/make_exps_page doesn't exist

### ISSUE THREAD

**Issue by lotsoffood** [amesar/mlflow-tools#1]
How does one install `mlflow-tools`? I've created the `conda` environment, but get an error when trying to `pip install .` from the `mlflow-tools` folder:

    writing manifest file '/tmp/pip-pip-egg-info-t_gg0e6g/mlflow_tools.egg-info/SOURCES.txt'
    package init file 'mlflow_tools/__init__.py' not found (or not a regular file)
    error: package directory 'mlflow_tools/make_exps_page' does not exist

Any thoughts?

**Comment by RBuractaon** [comment]
Latest commit to the repo has this fixed

**Comment by amesar** [comment]
Fixed in setup.py.
